<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nunit_schema_2.5.xsd" name="Pester" total="2" errors="0" failures="1" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2023-07-12" time="23:20:26">
  <environment user-domain="ASIAPACIFIC" nunit-version="2.5.8.0" clr-version="Unknown" cwd="C:\Git\HPE\TheBoredAdmin\Pester" platform="Microsoft Windows 10 Enterprise|C:\windows|\Device\Harddisk0\Partition4" machine-name="EUGI44JQW4" user="gautamd" os-version="10.0.19045" />
  <culture-info current-culture="en-IN" current-uiculture="en-GB" />
  <test-suite type="TestFixture" name="Pester" executed="True" result="Failure" success="False" time="0.2513" asserts="0" description="Pester">
    <results>
      <test-suite type="TestFixture" name=".\assert-mockcalled1.tests.ps1" executed="True" result="Failure" success="False" time="0.2513" asserts="0" description=".\assert-mockcalled1.tests.ps1">
        <results>
          <test-suite type="TestFixture" name="Do-Something" executed="True" result="Failure" success="False" time="0.2134" asserts="0" description="Do-Something">
            <results>
              <test-case description="get-content should be called twice" name="Do-Something.get-content should be called twice" time="0.0153" asserts="0" success="True" result="Success" executed="True" />
              <test-case description="should not try to read the C:\ShouldNotCall.txt file" name="Do-Something.should not try to read the C:\ShouldNotCall.txt file" time="0.0315" asserts="0" success="False" result="Failure" executed="True">
                <failure>
                  <message>Expected Get-Content to only be called with with parameters matching the specified filter, but 2 non-matching calls were made</message>
                  <stack-trace>at &lt;ScriptBlock&gt;, : line 11
11:         Assert-MockCalled -CommandName 'Get-Content' -ExclusiveFilter { $Path -eq 'C:\ShouldCall.txt' }</stack-trace>
                </failure>
              </test-case>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>